name: TTT App Project 
on: 
  push: 
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "app"
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm 
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test 

  deploy:
    needs: test
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          printf '%s' "$EC2_SSH_KEY" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
      - name: Testing EC2 connection
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i ~/.ssh/ec2_key.pem \
          "$EC2_USERNAME"@"$EC2_HOST" \
          echo "Connected to EC2 succsessfully"
      - name: Deploy
        run: echo "Deploying..."